# -*- coding: utf-8 -*-
"""Pandas Library Test L-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16-Zv9VidqIW3AI3N_IQjAkggNB931XSI
"""

import pandas as pd

########## DATAFRAME ################
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

tempDataFrame = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'],
                              'Sue': ['Pretty good.', 'Bland.']},
                             index=['Product A', 'Product B'])

########### SERIES #################
print(pd.Series([1, 2, 3, 4, 5]))

print(pd.Series(['Sudipta', 'Kumar', 'Das'], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='DataFrame A'))
print(pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A'))

########## READING DATA FILES #################
Mobile_data = pd.read_csv("C:/Users/User/Desktop/MACHINE LEARNING/DATA/test.csv")
print("Read Successful")

print(Mobile_data.shape)
print(Mobile_data.head())

print("Again ....")
Mobile_data = pd.read_csv("C:/Users/User/Desktop/MACHINE LEARNING/DATA/test.csv", index_col=1)
print(Mobile_data.head())

################ WRITING DATA FILES
tempDataFrame.to_csv('tempDataFrame.csv')
